dist:   trusty
sudo:   required

language:   c++

compiler:
    - g++

before_script:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        mkdir -p external/cmake
        pushd external/cmake
        wget https://cmake.org/files/v3.19/cmake-3.19.0-rc1-Linux-x86_64.sh
        chmod +x cmake-*-Linux-x86_64.sh
        ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
        export PATH="${PWD}/bin:$PATH"
        popd
      fi


env:
  global:
    secure: "qay6Q4jO6LpxVgbYvH772VobmsZSr3FCksLroIbvrna8g9p3Fb/QWZQqeHF8A38SXZxMSyE2druax7oG3sNUKAd7gxdU3u91eYnkQ+CjOzdFoCQmEIBsnc215TbX4mvtwO8emNL3ScIQzGPhWXFHXXHMG/wz0SJMSCUE/R5nF8hnM+St5Ci/HX2Ag4uTkY/rYs+Bqity/9gmvqA15hU+8MQRPw7297o2Ie87HdJzNqZgRI93kdPIG2HMiyTz1Gd9mWxVb75p/TOs5GX6ELjmBgY+Z13ZY7NxmDSb0hxm2Uesz0hv6L9VQRMzstE1hWQ4nLnRhQQBF3zbuLWSdenhmsJ0DgeKgSFcGHg3NvsPRWEXVAlTFzMget6QkzSs37UYmaFdZKQaI7gUU/M0f0/jBxEpOJqgEwcv7QtcF0m3etvV+Odyhc1ChMh5MvuBG6HnFMYqOjgge7ncG/QfIQYHHCRNg+VTPgsp6iAzAmi4DyJ967XRcQHcsQBfqYA7PQRzR83tSlPBrfr9o89NtrJwTdKutJ/5Qc1w8FQLk5ZtiXEFq45HyWcQu/xVOu+GL3HRhrL4c+fUs+GK5u5bGaiEhEhHIHKg6DH3pI/VvaR9SjN0ar/drrOtUHJEVS68H/aXhUm/LISSIk85/ZbMZOQJbdLxsXup669fnN45iUYpV4g="

matrix:
    include:

    - os: linux
      env:
        - TEST="test build"
      script:
        - mkdir build
        - cd build/
        - cmake ..
        - make
        - ./ClusterProg
        - cd ..
        - rm -rf build/
